[GroupWelcome]
enable = true
# å¡ç‰‡æ ·å¼, å¯é€‰å€¼: "é»˜è®¤", "éŸ³ä¹å¡ç‰‡", "éŸ³ä¹å¡ç‰‡1"
card_style = "éŸ³ä¹å¡ç‰‡1"
# é»˜è®¤æ ·å¼é…ç½®
welcome_title = "ğŸ‘çƒ­çƒˆæ¬¢è¿ğŸ‰"
welcome-message = "åŠ å…¥ç¾¤èŠï¼"
url = "https://sharefs.tx.kugou.com/202506121827/053e806abaf13fff124d246e984f7cfa/v3/d4740ce06e6f57eef352a04a32996d76/yp/full/ap1000_us0_pi409_s534812040.mp3" # é»˜è®¤å¡ç‰‡ç‚¹å‡»åè·³è½¬çš„é“¾æ¥
# éŸ³ä¹å¡ç‰‡æ ·å¼é…ç½®
music_url = "https://sharefs.tx.kugou.com/202506121827/053e806abaf13fff124d246e984f7cfa/v3/d4740ce06e6f57eef352a04a32996d76/yp/full/ap1000_us0_pi409_s534812040.mp3"
send-file = false